/*
 * ARM Cortex-A72 performance monitoring events
 *
 * Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
 * Copyright 2021, HENSOLDT Cyber GmbH
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

#pragma once

// Events are defined in the Cortex-A72 TRM. Most recent version as of today is
// "ARM 100095_0003_06_en" (2016-Dec-01, "Second release for r0p3"),
// section 11.8 "Performance Monitor Unit", "Events". The definitions for the
// Cortex-A72 core are aligned with the ARM Architecture Reference Manual for
// ARMv8. Most recent version as of today is "ARM DDI 0487G.a" (2021-Jan-22,
// "Initial Armv8.7 EAC release"). See section K3.1 "Arm recommendations for
// IMPLEMENTATION DEFINED event numbers"




#define SEL4BENCH_EVENT_SW_INCR	0x00
#define SEL4BENCH_EVENT_L1I_CACHE_REFILL	0x01
#define SEL4BENCH_EVENT_L1I_TLB_REFILL	0x02
#define SEL4BENCH_EVENT_L1D_CACHE_REFILL	0x03
#define SEL4BENCH_EVENT_L1D_CACHE	0x04
#define SEL4BENCH_EVENT_L1D_TLB_REFILL	0x05
#define SEL4BENCH_EVENT_INST_RETIRED	0x08
#define SEL4BENCH_EVENT_EXC_TAKEN	0x09
#define SEL4BENCH_EVENT_EXC_RETURN	0x0A
#define SEL4BENCH_EVENT_CID_WRITE_RETIRED	0x0B
#define SEL4BENCH_EVENT_BR_MIS_PRED	0x10
#define SEL4BENCH_EVENT_CPU_CYCLES	0x11
#define SEL4BENCH_EVENT_BR_PRED	0x12
#define SEL4BENCH_EVENT_MEM_ACCESS	0x13
#define SEL4BENCH_EVENT_L1I_CACHE	0x14
#define SEL4BENCH_EVENT_L1D_CACHE_WB	0x15
#define SEL4BENCH_EVENT_L2D_CACHE	0x16
#define SEL4BENCH_EVENT_L2D_CACHE_REFILL	0x17
#define SEL4BENCH_EVENT_L2D_CACHE_WB	0x18
#define SEL4BENCH_EVENT_BUS_ACCESS	0x19
#define SEL4BENCH_EVENT_MEMORY_ERROR	0x1A
#define SEL4BENCH_EVENT_INST_SPEC	0x1B
#define SEL4BENCH_EVENT_TTBR_WRITE_RETIRED	0x1C
#define SEL4BENCH_EVENT_BUS_CYCLES	0x1D
#define SEL4BENCH_EVENT_CHAIN	0x1E
#define SEL4BENCH_EVENT_L1D_CACHE_LD	0x40
#define SEL4BENCH_EVENT_L1D_CACHE_ST	0x41
#define SEL4BENCH_EVENT_L1D_CACHE_REFILL_LD	0x42
#define SEL4BENCH_EVENT_L1D_CACHE_REFILL_ST	0x43
#define SEL4BENCH_EVENT_L1D_CACHE_WB_VICTIM	0x46
#define SEL4BENCH_EVENT_L1D_CACHE_WB_CLEAN	0x47
#define SEL4BENCH_EVENT_L1D_CACHE_INVAL	0x48
#define SEL4BENCH_EVENT_L1D_TLB_REFILL_LD	0x4C
#define SEL4BENCH_EVENT_L1D_TLB_REFILL_ST	0x4D
#define SEL4BENCH_EVENT_L2D_CACHE_LD	0x50
#define SEL4BENCH_EVENT_L2D_CACHE_ST	0x51
#define SEL4BENCH_EVENT_L2D_CACHE_REFILL_LD	0x52
#define SEL4BENCH_EVENT_L2D_CACHE_REFILL_ST	0x53
#define SEL4BENCH_EVENT_L2D_CACHE_WB_VICTIM	0x56
#define SEL4BENCH_EVENT_L2D_CACHE_WB_CLEAN	0x57
#define SEL4BENCH_EVENT_L2D_CACHE_INVAL	0x58
#define SEL4BENCH_EVENT_BUS_ACCESS_LD	0x60
#define SEL4BENCH_EVENT_BUS_ACCESS_ST	0x61
#define SEL4BENCH_EVENT_BUS_ACCESS_SHARED	0x62
#define SEL4BENCH_EVENT_BUS_ACCESS_NOT_SHARED	0x63
#define SEL4BENCH_EVENT_BUS_ACCESS_NORMAL	0x64
#define SEL4BENCH_EVENT_BUS_ACCESS_PERIPH	0x65
#define SEL4BENCH_EVENT_MEM_ACCESS_LD	0x66
#define SEL4BENCH_EVENT_MEM_ACCESS_ST	0x67
#define SEL4BENCH_EVENT_UNALIGNED_LD_SPEC	0x68
#define SEL4BENCH_EVENT_UNALIGNED_ST_SPEC	0x69b
#define SEL4BENCH_EVENT_UNALIGNED_LDST_SPEC	0x6Ab
#define SEL4BENCH_EVENT_LDREX_SPEC	0x6C
#define SEL4BENCH_EVENT_STREX_PASS_SPEC	0x6D
#define SEL4BENCH_EVENT_STREX_FAIL_SPEC	0x6E
#define SEL4BENCH_EVENT_LD_SPEC	0x70
#define SEL4BENCH_EVENT_ST_SPEC	0x71
#define SEL4BENCH_EVENT_LDST_SPEC	0x72
#define SEL4BENCH_EVENT_DP_SPEC	0x73
#define SEL4BENCH_EVENT_ASE_SPEC	0x74
#define SEL4BENCH_EVENT_VFP_SPEC	0x75
#define SEL4BENCH_EVENT_PC_WRITE_SPEC	0x76
#define SEL4BENCH_EVENT_CRYPTO_SPEC	0x77
#define SEL4BENCH_EVENT_BR_IMMED_SPEC	0x78
#define SEL4BENCH_EVENT_BR_RETURN_SPEC	0x79
#define SEL4BENCH_EVENT_BR_INDIRECT_SPEC	0x7A
#define SEL4BENCH_EVENT_ISB_SPEC	0x7C
#define SEL4BENCH_EVENT_DSB_SPEC	0x7D
#define SEL4BENCH_EVENT_DMB_SPEC	0x7E
#define SEL4BENCH_EVENT_EXC_UNDEF	0x81
#define SEL4BENCH_EVENT_EXC_SVC	0x82
#define SEL4BENCH_EVENT_EXC_PABORT	0x83
#define SEL4BENCH_EVENT_EXC_DABORT	0x84
#define SEL4BENCH_EVENT_EXC_IRQ	0x86
#define SEL4BENCH_EVENT_EXC_FIQ	0x87
#define SEL4BENCH_EVENT_EXC_SMC	0x88
#define SEL4BENCH_EVENT_EXC_HVC	0x8A
#define SEL4BENCH_EVENT_EXC_TRAP_PABORT	0x8B
#define SEL4BENCH_EVENT_EXC_TRAP_DABORT	0x8C
#define SEL4BENCH_EVENT_EXC_TRAP_OTHER	0x8D
#define SEL4BENCH_EVENT_EXC_TRAP_IRQ	0x8E
#define SEL4BENCH_EVENT_EXC_TRAP_FIQ	0x8F
#define SEL4BENCH_EVENT_RC_LD_SPEC	0x90
#define SEL4BENCH_EVENT_RC_ST_SPEC	0x91